"""2022 World Cup results for holdout evaluation (Kaggle / RSSSF labels)."""

from __future__ import annotations

WC2022_RESULTS: dict[tuple[str, str], str] = {
    ("Qatar", "Ecuador"): "A",
    ("Qatar", "Senegal"): "A",
    ("Netherlands", "Ecuador"): "D",
    ("Ecuador", "Senegal"): "A",
    ("Netherlands", "Qatar"): "H",
    ("Senegal", "Ecuador"): "H",
    ("England", "Iran"): "H",
    ("United States", "Wales"): "D",
    ("Wales", "Iran"): "H",
    ("England", "United States"): "D",
    ("Wales", "England"): "A",
    ("Iran", "United States"): "A",
    ("Argentina", "Saudi Arabia"): "A",
    ("Mexico", "Poland"): "D",
    ("Poland", "Saudi Arabia"): "H",
    ("Argentina", "Mexico"): "H",
    ("Poland", "Argentina"): "A",
    ("Saudi Arabia", "Mexico"): "A",
    ("Denmark", "Tunisia"): "D",
    ("France", "Australia"): "H",
    ("Tunisia", "Australia"): "A",
    ("France", "Denmark"): "H",
    ("Tunisia", "France"): "A",
    ("Australia", "Denmark"): "A",
    ("Germany", "Japan"): "A",
    ("Spain", "Costa Rica"): "H",
    ("Japan", "Costa Rica"): "H",
    ("Spain", "Germany"): "D",
    ("Japan", "Spain"): "A",
    ("Costa Rica", "Germany"): "A",
    ("Morocco", "Croatia"): "D",
    ("Belgium", "Canada"): "H",
    ("Belgium", "Morocco"): "A",
    ("Croatia", "Canada"): "H",
    ("Croatia", "Belgium"): "D",
    ("Canada", "Morocco"): "A",
    ("Switzerland", "Cameroon"): "H",
    ("Brazil", "Serbia"): "H",
    ("Cameroon", "Serbia"): "H",
    ("Brazil", "Switzerland"): "D",
    ("Cameroon", "Brazil"): "H",
    ("Serbia", "Switzerland"): "A",
    ("Uruguay", "South Korea"): "D",
    ("Portugal", "Ghana"): "H",
    ("South Korea", "Ghana"): "H",
    ("Portugal", "Uruguay"): "H",
    ("Ghana", "Uruguay"): "A",
    ("South Korea", "Portugal"): "A",
    ("Netherlands", "United States"): "H",
    ("Argentina", "Australia"): "H",
    ("France", "Poland"): "H",
    ("England", "Senegal"): "H",
    ("Japan", "Croatia"): "D",
    ("Brazil", "South Korea"): "H",
    ("Morocco", "Spain"): "D",
    ("Portugal", "Switzerland"): "H",
    ("Croatia", "Brazil"): "D",
    ("Netherlands", "Argentina"): "D",
    ("Morocco", "Portugal"): "H",
    ("England", "France"): "A",
    ("Argentina", "Croatia"): "H",
    ("France", "Morocco"): "H",
    ("Croatia", "Morocco"): "H",
    ("Argentina", "France"): "D",
}


def label_wc2022(home: str, away: str) -> str | None:
    return WC2022_RESULTS.get((home, away))
